// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qovpgeqdkbqubpthaaxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvdnBnZXFka2JxdWJwdGhhYXhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NDY1OTIsImV4cCI6MjA2ODMyMjU5Mn0.bRVqgjCEI5vrt8U2uJG682pY9VN2c77za7u9wnIFdgk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});